---
# Vagrant config.
vagrant_ip: 192.168.40.15
vagrant_memory: 1024
vagrant_cpus: 2

# Drupal settings
drupal_domain: "dcm15.local"
drupal_core_path: "/drupal/docroot"
drupal_site_name: "DrupalCampMelbourne 2015"
drupal_install_profile: drupalcampmel
drupal_enable_modules: []
drupal_account_name: vagrant
drupal_account_pass: vagrant
drush_makefile_path: /drupal/stub.make
build_makefile: true
install_site: true

# Apache config
apache_vhosts:
  - {servername: "{{ drupal_domain }}", documentroot: "{{ drupal_core_path }}"}
  - {servername: "db.{{ drupal_domain }}", documentroot: "/opt/adminer", extra_parameters: "DirectoryIndex adminer.php"}
  - {servername: "logs.{{ drupal_domain }}", documentroot: "/usr/share/php/pimpmylog"}

installed_extras:
  - adminer
  - mailhog
  - memcached
  - pimpmylog
  - varnish
  - xdebug
  - xhprof
  - selenium
  - drupal-console
  # - solr

# Pimp my Log settings.
pimpmylog_install_dir: /usr/share/php/pimpmylog
pimpmylog_grant_all_privs: true