<?php
/**
 * @file
 * Code for the DrupalCampMelbourne: Core feature.
 */

/**
 * Features include.
 */
include_once 'drupalcampmel_core.features.inc';

/**
 * Include additional files.
 */
$dirname  = dirname(__FILE__);
$includes = file_scan_directory("{$dirname}/includes", '/.inc$/');
foreach (module_list() as $module) {
  if (isset($includes[$file = "{$dirname}/includes/{$module}.inc"])) {
    require_once $file;
  }
}
